In [41]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from PIL import Image 
import os

In [42]:
def load_images(folder , label , img_size=(64,64)):
    images=[]
    labels=[]
    for filename in os.listdir(folder):
        img_path = os.path.join(folder , filename)
        try:
            img = Image.open(img_path).convert("L")
            img = img.resize(img_size)
            img_array = np.array(img).flatten()
            images.append(img_array)
            labels.append(label)
            print(img)
        except:
            continue
    return images , labels

In [43]:
notumor_imgs ,notumor_labels = load_images(r"D:\brain tumor\Training\notumor" , 0)
glioma_imgs ,glioma_labels = load_images(r"D:\brain tumor\Training\glioma" , 1)
meningioma_imgs ,meningioma_labels = load_images(r"D:\brain tumor\Training\meningioma" , 2)
pituitary_imgs ,pituitary_labels = load_images(r"D:\brain tumor\Training\pituitary" , 3)


<PIL.Image.Image image mode=L size=64x64 at 0x2512ED4BC20>
<PIL.Image.Image image mode=L size=64x64 at 0x2512ED4BC20>
<PIL.Image.Image image mode=L size=64x64 at 0x2512ED4BC20>
<PIL.Image.Image image mode=L size=64x64 at 0x2512ED4BC20>
<PIL.Image.Image image mode=L size=64x64 at 0x2512ED4BC20>
<PIL.Image.Image image mode=L size=64x64 at 0x2512ED4BC20>
<PIL.Image.Image image mode=L size=64x64 at 0x2512ED4BC20>
<PIL.Image.Image image mode=L size=64x64 at 0x2512ED4BC20>
<PIL.Image.Image image mode=L size=64x64 at 0x2512ED4BC20>
<PIL.Image.Image image mode=L size=64x64 at 0x2512ED4BC20>
<PIL.Image.Image image mode=L size=64x64 at 0x2512ED4BC20>
<PIL.Image.Image image mode=L size=64x64 at 0x2512ED4BC20>
<PIL.Image.Image image mode=L size=64x64 at 0x2512ED4BC20>
<PIL.Image.Image image mode=L size=64x64 at 0x2512ED4BC20>
<PIL.Image.Image image mode=L size=64x64 at 0x2512ED4BC20>
<PIL.Image.Image image mode=L size=64x64 at 0x2512ED4BC20>
<PIL.Image.Image image mode=L size=64x64 at 0x2512ED4BC2

In [44]:
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.decomposition import PCA

X = notumor_imgs + glioma_imgs + pituitary_imgs + meningioma_imgs
y = notumor_labels + glioma_labels + pituitary_labels + meningioma_labels

X_train , X_test , y_train , y_test = train_test_split( X , y , train_size= 0.8 , random_state= 42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model_rf = RandomForestClassifier(random_state=42)
model_rf.fit(X_train , y_train)
y_pred2 = model_rf.predict(X_test)
print(f"training acc : {accuracy_score(y_train , model_rf.predict(X_train))}")
print(f"Testing acc : {accuracy_score(y_test , y_pred2)}")
print(confusion_matrix(y_test , y_pred2))

model_svm = SVC()
model_svm.fit(X_train , y_train)
y_pred3 = model_svm.predict(X_test)
print(f"training acc : {accuracy_score(y_train , model_svm.predict(X_train))}")
print(f"Testing acc : {accuracy_score(y_test , y_pred3)}")
print(confusion_matrix(y_test , y_pred3))


training acc : 1.0
Testing acc : 0.9291666666666667
[[373   0   5   2]
 [  8 289  35   6]
 [  8  13 322  16]
 [  0   0   9 354]]
training acc : 0.9496527777777778
Testing acc : 0.9048611111111111
[[365   3  10   2]
 [  9 299  29   1]
 [ 11  34 294  20]
 [  2   6  10 345]]


In [45]:
def test_img(img_path , model):
    img = Image.open(img_path).convert("L")
    img = img.resize((64,64))
    img_array = np.array(img).flatten().reshape(1,-1)
    img_scaled = scaler.transform(img_array)
    prediction = model.predict(img_scaled)
    return prediction

In [46]:
test_img(r"D:\brain tumor\Training\notumor\Te-no_2.jpg" , model_svm)

array([0])

In [47]:
import joblib
joblib.dump(model_rf , "model_rf.pkl")
joblib.dump(model_svm , "model_svm.pkl")
joblib.dump(scaler , "scaler.pkl")


['scaler.pkl']